# Generated by Django 3.2.19 on 2023-05-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='INN',
            field=models.IntegerField(null=True),
        ),
    ]
