# Generated by Django 3.2.19 on 2023-05-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inbox_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.CharField(blank=True, max_length=128, null=True)),
                ('date_document', models.DateField(blank=True, null=True)),
                ('date_send', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('sender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='send_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.CharField(blank=True, max_length=128, null=True)),
                ('date_document', models.DateField(blank=True, null=True)),
                ('date_send', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('inboxer', models.CharField(max_length=100)),
            ],
        ),
    ]
