# Generated by Django 3.2.19 on 2023-05-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox_documents',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='send_documents',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
